version: "3"

services:
  share_nacos2.1.1:
    image: nacos/nacos-server:v2.1.1
    container_name: share_nacos2.1.1
    restart: always
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.utf8
      - MODE=standalone
